### ISSUE TITLE
IntendedFor is a list of characters

### ISSUE THREAD

**Issue by mateuszpawlik** [Donders-Institute/bidscoin#127]
**Describe the bug**
The `IntendedFor` field in fmap json files stores a list of characters from a task file name.

**To reproduce**
1. Generate DICOM files using with [DICOM generator](https://frosch.cosy.sbg.ac.at/anc/bids-misc-scripts#generate-dicom-files) and the following configuration:
```json
[
  {
    "ImageType" : "anat",
    "SeriesDescription" : "T1w"
  },
  {
    "ImageType" : "magnitude",
    "SeriesDescription" : "fmap"
  },
  {
    "ImageType" : "phase",
    "SeriesDescription" : "fmap"
  },
  {
    "ImageType" : "fmri",
    "SeriesDescription" : "fmri1"
  },
  {
    "ImageType" : "fmri",
    "SeriesDescription" : "fmri2"
  },
  {
    "ImageType" : "fmri",
    "SeriesDescription" : "fmri3"
  }
]
```
2. Execute `dicomsort`.
3. Execute `bidsmapper` with the map:
```yml
Options:

  bidscoin:
    version: 3.7.0
    bidsignore: extra_data/
    subprefix: sub-
    sesprefix: ses-
    datatypes: [fmap, anat, func]   # A list of datatypes that are converted to BIDS
    unknowntypes: [extra_data]    # A list of datatypes that are converted to BIDS-like datatype folders
    ignoretypes: [exclude]        # A list of datatypes that are excluded / not converted to BIDS
  plugins:
    dcm2niix2bids:
      path: ''
      args: -b y -z n -i n
      anon: n # Not to shift acquisition dates.

DICOM:

  subject: <<filepath:/sub-(.*?)/>> #<<SourceFilePath>>
  session: <<filepath:/ses-(.*?)/>> #<<SourceFilePath>>

  anat:
  - provenance:
    attributes: &anat_dicomattr
      ImageType:
      ProtocolName:
      SeriesDescription:
    bids: &anat_bidsattr # Dummy if not referenced.
      suffix: T1w
    meta: &anat_metaattr
      OriginalSeriesDescription: <SeriesDescription>
  - provenance:
    attributes:
      SeriesDescription: (?i).*T1w.*
    bids:
      suffix: T1w
    meta:
      <<: *anat_metaattr

  func:
  - provenance:
    attributes: &func_dicomattr
      ImageType:
      ProtocolName:
      SeriesDescription:
    bids: &func_bidsattr # Dummy if not referenced.
      task: <SeriesDescription>
      suffix: bold
    meta: &func_metaattr
      OriginalSeriesDescription: <SeriesDescription>
  - provenance:
    attributes:
      <<: *func_dicomattr
      SeriesDescription: (?i)fmri.*
    bids:
      <<: *func_bidsattr
      task: <SeriesDescription:(?i)fmri(.*?)$>
    meta:
      <<: *func_metaattr

  fmap:
  - provenance:
    attributes: &fmap_dicomattr
      ImageType:
      ProtocolName:
      SeriesDescription:
      EchoNumbers:
    bids: &fmap_bidsattr # Dummy if not referenced.
      suffix: magnitude1
      run: <<1>>
    meta: &fmap_metaattr
      IntendedFor: <<task:[0:3]>>
  - provenance:
    attributes:
      <<: *fmap_dicomattr
      SeriesDescription: .*fmap.*
      ImageType: .*'M'.*
    bids:
      <<: *fmap_bidsattr
      suffix: magnitude2 # Due to magnitude1 and magnitude2 images in the same series (Siemens). dcm2niix will deal with it correctly.
    meta:
      <<: *fmap_metaattr
  - provenance:
    attributes:
      <<: *fmap_dicomattr
      SeriesDescription: .*fmap.*
      ImageType: '[''ORIGINAL'', ''PRIMARY'', ''P'', ''ND'']'
    bids:
      <<: *fmap_bidsattr
      suffix: phasediff
    meta:
      <<: *fmap_metaattr
```
4. Execute `bidscoiner`.
5. View any fmap json file and see the characters in the `IntendedFor` field, for example:
```
"IntendedFor": [
        "f",
        "u",
        "n",
        "c",
        "/",
        "s",
        "u",
        "b",
        "-",
        "1",
        "_",
        "t",
        "a",
        "s",
        "k",
        "-",
        "1",
        "_",
        "b",
        "o",
        "l",
        "d",
        ".",
        "n",
        "i",
        "i",
        "f",
        "u",
        "n",
        "c",
        "/",
        "s",
        "u",
        "b",
        "-",
        "1",
        "_",
        "t",
        "a",
        "s",
        "k",
        "-",
        "2",
        "_",
        "b",
        "o",
        "l",
        "d",
        ".",
        "n",
        "i",
        "i",
        "f",
        "u",
        "n",
        "c",
        "/",
        "s",
        "u",
        "b",
        "-",
        "1",
        "_",
        "t",
        "a",
        "s",
        "k",
        "-",
        "3",
        "_",
        "b",
        "o",
        "l",
        "d",
        ".",
        "n",
        "i",
        "i"
    ],
```

**Expected behavior**
The file name in `IntendedFor` fiels is stored as string and not as a list of characters.

**Screenshots**

**Software version**
 - BIDScoin version 7ae1f58
 - OS Debian 10
