### ISSUE TITLE
'vox' field does not get parsed from bidsmap

### ISSUE THREAD

**Issue by schorschinho** [Donders-Institute/bidscoin#157]
**Describe the bug**
I have added an entry in the `vox` field in my bidsmap:
```
    attributes:
      examination_name: ''
      scan_id: PRESS
      echo_time: '30'
      repetition_time: '2000'
      samples: '2048'
      averages: '48'
      ap_size: '30'
      lr_size: '26'
      cc_size: '26'
    bids:
      task:
      acq: press
      inv:
      nuc:
      vox: cso                                       ## <-------------- this field right here
      type:
      run: <<1>>
      suffix: svs
```

Unfortunately, `vox` doesn't seem to get picked up. All other fields are correctly parsed into the BIDS output filename. The `vox` entry doesn't show up in `bidseditor` and also does not appear in the output files' filenames generated by `bidscoiner`.

![Screenshot 2022-10-12 150403](https://user-images.githubusercontent.com/16669943/195426786-fe884bf0-272a-44e9-b821-ced66066bc90.png)

**Comment by marcelzwiers** [comment]
That's because `vox` is not a BIDS-compliant field? BIDScoin checks for that and makes sure to produce valid output

**Comment by marcelzwiers** [comment]
It should work (i.e. include the vox key-value pair) if you make it an `extra_data` datatype

**Comment by schorschinho** [comment]
Thanks a lot. I hadn't added the `vox` field manually, it was just there right in the bidsmap template, so I assumed it'd be BIDS-compliant and went ahead and populated it!

Hmm, I'd really like to be able to use the mrs datatype. The BIDS-MRS extension proposal has a bunch of MRS-specific labels:
```
sub-<label>[_ses-<label>][_task-<label>][_acq-<label>][_rec-<label>][_run-<index>][_echo-<index>][_inv-<index>][_nuc-<label>][_voi-<label>]_<suffix>.nii[.gz]
``` 
(https://docs.google.com/document/d/1pWCb02YNv5W-UZZja24fZrdXLm4X7knXMiZI7E2z7mY/edit#)
Is it possible for

**Comment by marcelzwiers** [comment]
Ah, I see. Well, I think I tried to include as much from the BEPs as I could, but I don't do MRS myself -- which is why I didn't notice that BIDScoin's BIDS validation procedures stripped the vox field (as this field is not yet part of BIDS). I'll see if I can make the routines for this BIDS compliance optional

**Comment by schorschinho** [comment]
Fantastic. Thank you so much again for being so responsive and receptive.

**Comment by marcelzwiers** [comment]
Mhhh, I am now building the bids filename from the entities in this BIDS schema file: https://github.com/bids-standard/bids-specification/blob/master/src/schema/rules/entities.yaml
`Voxel` (vox) is not in there (yet), which is the root of this issue. However, I intentionally designed it like this, so that even a faulty bidsmap still produces BIDS-valid output -- I considered that more important than the BEPs. I think making it a switch is doable

**Comment by marcelzwiers** [comment]
I have implemented it such that BIDS compliance is now only enforced on datatypes that are not in `.bidsignore`. I haven't fully tested things, but you can try it out yourself with you upgrade your install to the latest github commit:
```console
pip install --upgrade git+https://github.com/Donders-Institute/bidscoin
```

**Comment by schorschinho** [comment]
Hi Marcel,

I upgraded my bidscoin install but `vox` is still not picked up, unfortunately. It's not displayed in the bidseditor, and no `vox` key-value label pair is added to the filename.

My source data is organized as follows:
```
raw
|-- sub-001
|   |-- ses-01
|   |   |-- CSO
|   |   |   |-- subjectname_PRESS_raw_act.sdat
|   |   |   |-- subjectname_PRESS_raw_act.spar
|   |   |   |-- subjectname_PRESS_raw_ref.sdat
|   |   |   |-- subjectname_PRESS_raw_ref.spar
|   |   |-- PCC
|   |   |   |-- subjectname_PRESS_raw_act.sdat
|   |   |   |-- subjectname_PRESS_raw_act.spar
|   |   |   |-- subjectname_PRESS_raw_ref.sdat
|   |   |   |-- subjectname_PRESS_raw_ref.spar
```

Here are the relevant attributes from the bidsmap:
```
    properties:
      filepath: .*CSO.*
      filename: .*raw_act.*
      filesize:
      nrfiles:
    attributes:
      examination_name: ''
      scan_id: PRESS
      echo_time: '30'
      repetition_time: '2000'
      samples: '2048'
      averages: '48'
      ap_size: '30'
      lr_size: '26'
      cc_size: '26'
    bids:
      task:
      acq: press
      inv:
      nuc:
      vox: cso
      type:
      run: <<1>>
      suffix: svs
```

I can successfully use the wildcards to map filenames containing the string `raw_act` to use the BIDS suffix `svs` and those containing the string `raw_ref` to use the suffix `ref`. But I still fail to do the same to make the distinction for filepaths containing `CSO` or `PCC` so they successfully map on the `vox` field being `cso` or `pcc`.

Appreciate any help :)
Thanks,
Georg
