### ISSUE TITLE
Edit filesystem matching

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/bidscoin#68]
BIDScoin supports run-item matching using filesystem properties, like this:

```yaml
filesystem:
  path: ~                     # E.g. .*Parkinson.* or ['.*phantom.*', '.*bottle.*']
  name: ~                     # E.g. .*fmap.* or ['.*fieldmap.*', '.*fmap.*']
  size: ~                     # E.g. 245870 or [245869, 245870, 245871]
```

However, curreently this cannot be edited in the bidseditor
