### ISSUE TITLE
Skipping fieldmaps in bidscoiner but not bidseditor

### ISSUE THREAD

**Issue by merit-xx** [Donders-Institute/bidscoin#70]
Hi,

I am new to the BIDS world, apologies if this is already explained elsewhere/has an obvious solution I am missing.

I am seeing my fieldmaps fine in the bidseditor and they are listed in the .yaml file, but when I run the bidscoiner I get the following errors:
```
2021-04-23 11:51:13 - bidscoin - ERROR Skipping unknown 'extra_data' run: ~/Desktop/fMRI/S1_sourcedata/sub-01/ses-01/SPINECHOFIELDMAP_AP_0007/TEST_CC_1.MR.STUDIES_PSYCHOLOGY.0007.0001.2021.03.30.16.17.38.160266.61035700.IMA
-> Re-run the bidsmapper and delete ~/Desktop/fMRI/S1_modulated_data/bidscoin_out/sub-01/ses-01 to solve this warning
2021-04-23 11:51:13 - bidscoin - ERROR Skipping unknown 'extra_data' run: ~/Desktop/fMRI/S1_sourcedata/sub-01/ses-01/SPINECHOFIELDMAP_PA_0008/TEST_CC_1.MR.STUDIES_PSYCHOLOGY.0008.0001.2021.03.30.16.17.38.160266.61036726.IMA
-> Re-run the bidsmapper and delete ~/Desktop/fMRI/S1_modulated_data/bidscoin_out/sub-01/ses-01 to solve this warning
```

Here is the section from the bidsmap.yaml file:
```
fmap:       # ----------------------- All fieldmap runs ----------------------
  - provenance: ~/Desktop/fMRI/S1_sourcedata/sub-01/ses-01/SPINECHOFIELDMAP_AP_0007/TEST_CC_1.MR.STUDIES_PSYCHOLOGY.0007.0001.2021.03.30.16.17.38.160266.61035700.IMA
    attributes:
      ProtocolName: SpinEchoFieldMap_AP
      ScanningSequence: EP
      Modality: MR
      SeriesDescription: SpinEchoFieldMap_AP
      ImageType: "['ORIGINAL', 'PRIMARY', 'M', 'ND', 'MOSAIC']"
      SequenceName: epse2d1_104
      SequenceVariant: SK
      MRAcquisitionType: 2D
      SliceThickness: '2'
      FlipAngle: '90'
      EchoNumbers: 1
      EchoTime: '66'
      RepetitionTime: '8000'
      PhaseEncodingDirection: j-
    bids:
      acq: SpinEchoFieldMapAP
      ce:
      dir: COL
      run: <<1>>
      suffix: epi
      IntendedFor: task
  - provenance: ~/Desktop/fMRI/S1_sourcedata/sub-01/ses-01/SPINECHOFIELDMAP_PA_0008/TEST_CC_1.MR.STUDIES_PSYCHOLOGY.0008.0001.2021.03.30.16.17.38.160266.61036726.IMA
    attributes:
      ProtocolName: SpinEchoFieldMap_PA
      ScanningSequence: EP
      Modality: MR
      SeriesDescription: SpinEchoFieldMap_PA
      ImageType: "['ORIGINAL', 'PRIMARY', 'M', 'ND', 'MOSAIC']"
      SequenceName: epse2d1_104
      SequenceVariant: SK
      MRAcquisitionType: 2D
      SliceThickness: '2'
      FlipAngle: '90'
      EchoNumbers: 1
      EchoTime: '66'
      RepetitionTime: '8000'
      PhaseEncodingDirection: j
    bids:
      acq: SpinEchoFieldMapPA
      ce:
      dir: COL
      run: <<1>>
      suffix: epi
      IntendedFor: task
```
Why does bidscoiner not recognise the fieldmaps? 
Thanks, any help is really appreciated!
