### ISSUE TITLE
Exclude patterns in bidsmap, or provenance priorities

### ISSUE THREAD

**Issue by astewartau** [Donders-Institute/bidscoin#72]
Thanks for all the great work on bidscoin! I am using it for a publicly available and automated processing pipeline for QSM (QSMxT). Could the functionality to _exclude_ certain patterns from being matched be implemented for use in a bidsmap file? Alternatively, could a priority be given to each provenance, such that if a series matches a higher-priority provenance, it is not checked against any other provenances? As far as I know, avoiding certain patterns is not possible currently, and it requires the series to be manually removed from the DICOM folder prior to running bidscoin.

This is my use case:

- I want to match `anat` series' with the `ProtocolName` matching `*gre*`
- I do _not_ want to match series' with the `ProtocolName` `*swi*` - these should be considered `extra_data`
- I tried creating a provenance to match the `ProtocolName` `*swi*` in `extra_data`
- The `*swi*` provenance is ignored in favor of the `anat` `*gre*` provenance when the `ProtocolName` matches both `*swi*` and `*gre*`
- I would like to be able to specifically exclude `*swi*` from being matched by the `anat` provenance, _or_ a way to specify the priority for each provenance - ie. giving the `*swi*` provenance a higher priority would move it to `extra_data` without then checking whether it matches the `*gre*` provenance.

This is my bidsmap.yaml file:

```
# --------------------------------------------------------------------------------
# This is a bidsmap YAML file with the key-value mappings for the different BIDS
# modalities (anat, func, dwi, etc). The modality attributes are the keys that map
# onto the BIDS labels. The bidsmap data-structure should be 5 levels deep:
# dict > dict > list > dict > dict
#
# NB:
# 1) Edit the bidsmap file to your needs before feeding it to bidscoiner.py
# 2) (Institute) users may create their own bidsmap_[template].yaml or
#    bidsmap_[sample].yaml file
#
# For more information, see:
# https://github.com/Donders-Institute/bidscoin
# https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
# --------------------------------------------------------------------------------


Options:
# --------------------------------------------------------------------------------
# General options
# --------------------------------------------------------------------------------
  bidscoin:
    version: 3.0.8                # BIDScoin version (should correspond with the version in ../bidscoin/version.txt)
    bidsignore: extra_data/       # Semicolon-separated list of entries that are added to the .bidsignore file (for more info, see BIDS specifications), e.g. extra_data/;pet/;myfile.txt;yourfile.csv
  dcm2niix:                       # See dcm2niix -h and https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#General_Usage for more info
    path: echo;                   # Command to set the path to dcm2niix (note the semi-colon), e.g. module add dcm2niix/1.0.20180622; or PATH=/opt/dcm2niix/bin:$PATH; or /opt/dcm2niix/bin/ or '"C:\Program Files\dcm2niix\"' (note the quotes to deal with the whitespace)
    args: -b y -z y -i n          # Argument string that is passed to dcm2niix. Tip: SPM users may want to use '-z n' (which produces unzipped nifti's, see dcm2niix -h for more information)


PlugIns: []
DICOM:
# --------------------------------------------------------------------------------
# DICOM key-value heuristics (DICOM fields that are mapped to the BIDS labels)
# --------------------------------------------------------------------------------
  subject: <<SourceFilePath>>     # <<SourceFilePath>> extracts the subject label from the source directory during bidscoiner runtime. A DICOM attribute can also be used as subject-label instead, e.g. <PatientID>
  session: <<SourceFilePath>>     # <<SourceFilePath>> extracts the session label from the source directory during bidscoiner runtime. A DICOM attribute can also be used as session-label instead, e.g. <StudyID>
  anat:       # ----------------------- All anatomical series --------------------
  - provenance: ~
    attributes:
      Modality: MR
      ProtocolName: ~
      SeriesDescription: ['*t1*', '*T1*', '*MPRAGE*', '*MP2RAGE*']
      ImageType: 'M'
      SequenceName: ~
      SequenceVariant: ~
      ScanningSequence: ~
      MRAcquisitionType: ~
      SliceThickness: ~
      FlipAngle: ~
      EchoNumbers: ~
      EchoTime: ~
      RepetitionTime: ~
      PhaseEncodingDirection: ~
    bids:
      acq: T1w
      rec:
      ce:
      task:
      echo: <EchoNumber>
      dir:
      run: <<1>>
      mod:
      suffix: magnitude
  - provenance: ~
    attributes:
      Modality: MR
      ProtocolName: ['*ASPIRE*', '*Aspire*', '*aspire*', '*GRE*','*gre*','*epi*','*EPI*','*QSM*','*qsm*', '*T2Star*', '*T2star*', '*t2star*', '*T2\**', '*t2\**']
      SeriesDescription: ~
      ImageType: 'M'
      SequenceName: ~
      SequenceVariant: ~
      ScanningSequence: ~
      MRAcquisitionType: ~
      SliceThickness: ~
      FlipAngle: ~
      EchoNumbers: ~
      EchoTime: ~
      RepetitionTime: ~
      PhaseEncodingDirection: ~
    bids:
      acq: qsm
      rec:
      ce:
      task:
      echo: <EchoNumber>
      dir:
      run: <<1>>
      mod:
      suffix: magnitude
  - provenance: ~
    attributes:
      Modality: MR
      ProtocolName: ['*ASPIRE*', '*Aspire*', '*aspire*', '*GRE*','*gre*','*epi*','*EPI*','*QSM*','*qsm*', '*T2Star*', '*T2star*', '*t2star*', '*T2\**', '*t2\**']
      SeriesDescription: ~
      ImageType: 'P'
      SequenceName: ~
      SequenceVariant: ~
      ScanningSequence: ~
      MRAcquisitionType: ~
      SliceThickness: ~
      FlipAngle: ~
      EchoNumbers: ~
      EchoTime: ~
      RepetitionTime: ~
      PhaseEncodingDirection: ~
    bids:
      acq: qsm
      rec:
      ce:
      task:
      echo: <EchoNumber>
      dir:
      run: <<1>>
      mod:
      suffix: phase
  func:       # ----------------------- All functional series --------------------
  dwi:        # ----------------------- All diffusion series ---------------------
  fmap:       # ----------------------- All fieldmap series ----------------------
  beh:        # ----------------------- All behavioural data ---------------------
  pet:        # ----------------------- All PET series ---------------------------
  extra_data: # ----------------------- All extra data ---------------------------
  - provenance: ~
    attributes:
      Modality: MR
      ProtocolName: '*swi*'
      SeriesDescription: ~
      ImageType: ~
      SequenceName: ~
      SequenceVariant: ~
      ScanningSequence: ~
      MRAcquisitionType: ~
      SliceThickness: ~
      FlipAngle: ~
      EchoNumbers: ~
      EchoTime: ~
      RepetitionTime: ~
      PhaseEncodingDirection: ~
    bids:
      acq: swi
      rec:
      ce:
      task:
      echo:
      dir:
      run: <<1>>
      mod:
      suffix:
  leave_out:  # ----------------------- Data that will be left out ---------------
PAR:
# --------------------------------------------------------------------------------
# PAR key-value heuristics (Philips PAR fields that are mapped to the BIDS labels)
# --------------------------------------------------------------------------------


P7:
# --------------------------------------------------------------------------------
# P*.7 key-value heuristics (GE fields that are mapped to the BIDS labels)
# --------------------------------------------------------------------------------


Nifti:
# --------------------------------------------------------------------------------
# Nifti key-value heuristics (Nifti fields that are mapped to the BIDS labels)
# --------------------------------------------------------------------------------


FileSystem:
# --------------------------------------------------------------------------------
# File system key-value heuristics (these file- and foldernames will be mapped
# to the BIDS labels; Special substitutions can be performed using python's
# Format Specification Mini-Language)
# --------------------------------------------------------------------------------
  subject: <<SourceFilePath>>       # <<SourceFilePath>> extracts the subject label from the source directory during bidscoiner runtime
  session: <<SourceFilePath>>       # <<SourceFilePath>> extracts the session label from the source directory during bidscoiner runtime
  anat:       # ----------------------- All anatomical series --------------------
  func:       # ----------------------- All functional series --------------------
  dwi:        # ----------------------- All diffusion series ---------------------
  fmap:       # ----------------------- All fieldmap series ----------------------
  beh:        # ----------------------- All behavioural data ---------------------
  extra_data: # ----------------------- All extra data ---------------------------
  leave_out:  # ----------------------- Data that will be left out ---------------

```

**Comment by marcelzwiers** [comment]
An exclude pattern in the version you are using can be made with adding matching run-items to the `leave-out` datatype. Another thing to note is that, within a datatype (say `anat`), matches are searched for from top to bottom and the datatypes are searched for in this order:

```python
bidsmodalities  = ('fmap', 'anat', 'func', 'dwi', 'beh', 'pet') 
ignoremodality  = 'leave_out'
unknownmodality = 'extra_data'

# Get_matching_run() uses this order to search for a match
matchingorder = (ignoremodality,) + bidsmodalities + (unknownmodality,) 
```
Another thing to exploit is adding other criteria (other than the ProtocolName) that match the series that you want to match, but not the other series. Take a look at this (bidsmap_dccn) example:

```yaml
  - provenance: ~
    attributes:
      <<: *anatattributes_dicom
      SeriesDescription: '*tse_vfl*'
      SequenceVariant: "['SK', 'SP']"
      ScanningSequence: SE
    bids:
      <<: *anatbids_dicom
      suffix: T2w
```

So the `SeriesDescription` is pretty liberal, but the match is made more specific by adding e.g. the `ScanningSequence` requirement.

I hope this helps, but more importantly for you perhaps, is that I'm about to release a new version (3.6) which is adding the functionality you are asking for, namely by using regular expressions to perform the match. As you probably know regular expressions can be hard, but they are also very powerful and I think with the new bidscoin version you can handle virtually any use case out there (I believe they are Turing complete :-)). And another goodie is that in 3.6, you can also perform matching on the file-system properties (such as the filename, size or number of files in the folder)

It's a really good release, 3.6, and I think you can already use it for your purpose if you do the pip install from github. I only want to update the documentation now, and then release it. :-)
