### ISSUE TITLE
[ENH] passing additional information to the plugins

### ISSUE THREAD

**Issue by yjmantilla** [Donders-Institute/bidscoin#85]
For the sovabids plugin I needed to pass information from the yaml file to the get_attribute function of the plugin. Currently what goes to the plugin (through the get_attribute function) is limited to be (dataformat,sourcefile,attribute).
So to be able to pass additional information I used the plugin options configuration of the yaml file. For example:

```yaml
    sova2coin:            #module add sovabids #
      rules_file : y:\code\sovabids\examples\bidscoin_example_rules.yml
      non-bids:
        path_pattern : /%ignore%/ses-%entities.session%/%entities.task%/sub-%entities.subject%.vhdr #USE POSIX

```

I declare my function as : 

```python
def get_attribute(dataformat: str, sourcefile: Path, attribute: str,opt:dict=None) -> Union[str, int]:
    if dataformat == 'EEG':
        return get_eegfield(attribute, sourcefile,opt)
```

And I modified the bidscoin/bids.py/Datasource/attributes methods with the following:

```python
        for plugin, options in self.plugins.items():
            module = bidscoin.import_plugin(plugin, ('get_attribute',))
            if module:
                if module.get_attribute.__code__.co_argcount == 4:
                    attributeval = module.get_attribute(self.dataformat, self.path, attributekey,self.plugins)
                else:
                    attributeval = module.get_attribute(self.dataformat, self.path, attributekey)
```

Which just passes the plugin options to that function. Is hacky but maybe is a good idea to explore to allow some flexibility on the plugin needs.

Let me know if a PR should be done on my part
