### ISSUE TITLE
Two fmap run-items with equal matching rules in the dccn template

### ISSUE THREAD

**Issue by mateuszpawlik** [Donders-Institute/bidscoin#98]
I've found two run-items in the dccn template, one after another, with equal matching rules. They differ in the BIDS suffix. Does it mean that the second run-item is obsolete?

[Line 666](https://github.com/Donders-Institute/bidscoin/blob/748ea2ba537b06d8eee54ac7217b909bdf91a812/bidscoin/heuristics/bidsmap_dccn.yaml#L666):
```
  - provenance:
    attributes:
      <<: *fmap_dicomattr
      ProtocolName: (?i).*(fmap|field.?map|B0.?map).*
    bids:
      <<: *fmap_dicoment_fieldmaps
      suffix: fieldmap
    meta:
      IntendedFor:
```
and [line 675](https://github.com/Donders-Institute/bidscoin/blob/748ea2ba537b06d8eee54ac7217b909bdf91a812/bidscoin/heuristics/bidsmap_dccn.yaml#L675)
```
  - provenance:
    attributes:
      <<: *fmap_dicomattr
      ProtocolName: (?i).*(fmap|field.?map|B0.?map).*
    bids:
      <<: *fmap_dicoment_fieldmaps
      suffix: magnitude
    meta:
      IntendedFor:
```
